# version key removed (obsolete)
services:
  app:
    build: .
    container_name: tonie_converter
    environment:
      NAME: Tonie-Prepper
      BACKEND: pipe
      DEVICE: /fifo/spotout
      BITRATE: "320"
      VOLUME_CTRL: fixed
      INITIAL_VOLUME: "100"
      TZ: Europe/Berlin
      PRESET: speech
      TARGET_LUFS: "-18"
      TRUE_PEAK: "-1.0"
      BITRATE_K: "96"
      MONO: "1"
      MAX_TONIE_MIN: "90"
      UI_PASSWORD: ""
    volumes:
      - spotpipe:/fifo
      - ./output:/app/output
      - ./db:/app/db
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/status"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped

volumes:
  spotpipe:
    driver: local
